baseurl = "http://www.uncontainer.com/"
languageCode = "en-us"
title = "Uncontainer - Docker, Containers, Kubernetes, AWS"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Uncontainer"
	description = "Uncontainer - Devops, Docker, Containers, Kubernetes, AWS"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Uncontainer"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Containers free your infrastructure from its shackles. UnContain your mission critical systems "
		subtitle   = "Containers (like Docker, rkt, kubernetes) is to infrastructure what object oriented programming is to bad code. "
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "We at Uncontainer, allow you to cleanly separate what has traditionally has been dumped on a single big server (which you can still use). Everything is concise, easy-to-understand, and easily replace-able components. <br/> <br/> For example, with Docker, it's easy to swap out your Apache container for your nginx container in a way that doesn't affect your application because it can run fine with any of your web server containers."


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Docker expertise"
            description = "Create containers out of every component. Build all your complex dependencies in an easy, portable way"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "Everything we build is designed to be put in production in gradual steps. So you dont have to worry about risky cutovers"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Built to scale"
            description = "We harness Kubernetes to help you scale beyond a few machines!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Watch how Kubernetes and Docker helps build a bank! "

		[params.aside.button]
			text = "Building a bank with Kubernetes at Monzo"
			link = "//www.youtube.com/watch?v=YkOY7DgXKyw"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Give us a buzz or drop us an email. We dont charge to talk to people ;) We dont have secret algorithms... just deep technology experience and lots of hard work"
		phone = "+91-98114-52-098"
		email = "hello@uncontainer.com"

	# Google Maps section
	 [params.location]
	 	latitude  = "28.4979537"
	 	longitude = "77.1596063"
	 	maps_api_key = ""
